// Datos compartidos para los diagnosticos de Mentora y Mentoreada
const DIAG_DATA = {
    lectura: {
        words: 393,
        text: "El líderazgo femenino en América Latina está en un momento de inflexión. Según el Informe Global de Género 2024 del Foro Económico Mundíal, la región ha avanzado en educación y salud, pero la brecha política y económica sigue siendo significativa. Las mujeres ocupan menos del 30 por ciento de los puestos directivos en las empresas más grandes, a pesar de que en muchos países latinoamericanos son mayoría en las universidades y obtienen mejores promedios académicos que los hombres. Esta contradicción no es casual. Refleja barreras estructurales, culturales y psicológicas que operan simultáneamente para limitar el ascenso profesional de las mujeres.\n\nLa investigación académica ha identificado varios mecanismos que explican está brecha. En primer lugar, la psicóloga social Shelley Correll, de la Universidad Stanford, demostró a través de numerosos experimentos que las expectativas de género afectan las evaluaciónes de competencia incluso cuando el desempeño es idéntico. En uno de sus estudios más citados, publicado en American Journal of Sociology, Correll encontró que cuando hombres y mujeres presentaban la misma calificación académica, los evaluadores seguían considerando que los hombres tenían mayor capacidad matemática. Este sesgo no siempre es consciente, pero sí sistemático, y se reproduce en procesos de contratación, promoción y asignación de proyectos.\n\nEn segundo lugar, el trabajo de Herminia Ibarra en INSEAD y London Business School muestra que el acceso a redes informales de poder es un determinante crítico del avance profesional. Las redes no son solo relaciones personales; son canales por donde circulan información privilegiada, oportunidades visibles y validación social. Ibarra encontró que las mujeres tienden a tener redes más cercanas y homogéneas, mientras que los hombres suelen construir redes más amplias y estratégicas. Esta diferencia no es un defecto individual, sino el resultado de años de dinámicas sociales que asignan espacios de sociabilidad diferentes a hombres y mujeres.\n\nFinalmente, el concepto de seguridad psicológica, desarrollado por Amy Edmondson en Harvard Business School, ayuda a entender por qué muchas mujeres no se arriesgan a visibilizar sus ideas o a pedir lo que necesitan. Edmondson define la seguridad psicológica como la creencia compartida de que un equipo es seguro para tomar riesgos interpersonales. En ambientes donde está seguridad es baja, las personas minoritarias —incluidas las mujeres— silencian sus opiniónes para evitar repercusiones. Construir líderazgo femenino efectivo requiere, por tanto, intervenir simultáneamente en las estructuras organizaciónales, las redes de poder y las creencias individuales.",
        questions: [
            { q: "Según el texto, ¿qué porcentaje aproximado de puestos directivos ocupan las mujeres en las empresas más grandes de América Latina?", options: ["A) Menos del 20%", "B) Menos del 30%", "C) Alrededor del 40%", "D) Más del 50%"], answer: 1 },
            { q: "¿Qué encontró Shelley Correll en sus estudios sobre evaluaciónes de competencia?", options: ["A) Las mujeres son evaluadas de forma más estricta en humanidades.", "B) Con la misma calificación, se percibe a los hombres con mayor capacidad matemática.", "C) Los hombres obtienen mejores promedios académicos generales.", "D) Las mujeres prefieren proyectos menos técnicos."], answer: 1 },
            { q: "Según Herminia Ibarra, ¿cuál es una característica de las redes informales de las mujeres en comparación con las de los hombres?", options: ["A) Son más amplias pero menos profundas.", "B) Son más estratégicas y diversas.", "C) Son más cercanas y homogéneas.", "D) Se centran exclusivamente en el entorno familiar."], answer: 2 },
            { q: "¿Cuál es la definición de 'seguridad psicológica' según Amy Edmondson?", options: ["A) La capacidad individual de manejar el estrés en el trabajo.", "B) La creencia compartida de que un equipo es seguro para tomar riesgos interpersonales.", "C) Políticas de recursos humanos contra el acoso laboral.", "D) La confianza en la estabilidad financiera de la empresa."], answer: 1 },
            { q: "Según el texto, ¿cuál no es uno de los elementos en los que se debe intervenir para construir un líderazgo femenino efectivo?", options: ["A) Las estructuras organizaciónales.", "B) Las redes de poder.", "C) Las creencias individuales.", "D) Los promedios académicos universitarios."], answer: 3 }
        ]
    },
    brechas: [
        { q: "Cuándo piensas en ella como líder, ¿que imagen aparece primero?", options: ["No se ve como líder", "Se ve líderando en ciertas situaciónes, pero no en otras", "Se ve como líder en formacion", "Se ve como líder consolidada"], dimension: "Identidad de Liderazgo", correct: 3 },
        { q: "En una reunión importante, ¿con que frecuencia toma la palabra para dirigir la conversacion?", options: ["Casi nunca", "Solo si le piden opinión", "Cuándo tiene algo claro que aportar", "Frecuentemente, incluso para abrir temas"], dimension: "Identidad de Liderazgo", correct: 3 },
        { q: "Si su equipo la eligiera como referente natural, ¿que tan probable crees que sea?", options: ["Muy poco probable", "Posible en algunos contextos", "Probable si se esfuerza", "Muy probable"], dimension: "Identidad de Liderazgo", correct: 3 },
        { q: "¿Con que frecuencia dice 'yo lídero esto' o asume la responsabilidad de un resultado grupal?", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente"], dimension: "Identidad de Liderazgo", correct: 3 },
        { q: "Cuándo imaginas su carrera en 5 años, ¿la ves en un puesto de líderazgo?", options: ["No me lo imagino", "Me cuestá imaginarlo", "Lo imagino con esfuerzo", "Lo imagino claramente"], dimension: "Identidad de Liderazgo", correct: 3 },
        { q: "Ante una crítica inesperada en publico, ¿que suele hacer?", options: ["Se bloquea o se pone a la defensiva", "Se incomoda pero intenta mantener la calma", "Respira y pide clarificacion", "Procesa la informacion y responde con serenidad"], dimension: "Gestion Emocional", correct: 3 },
        { q: "¿Con que frecuencia sus emociónes afectan sus decisiónes importantes?", options: ["Siempre", "Frecuentemente", "A veces", "Casi nunca"], dimension: "Gestion Emocional", correct: 3 },
        { q: "Cuándo siente estres intenso, ¿tiene estrategias para regularse?", options: ["No tiene ninguna", "Alguna pero no siempre funcionan", "Tiene algunas que usa", "Tiene varias estrategias probadas"], dimension: "Gestion Emocional", correct: 3 },
        { q: "En conflictos interpersonales, ¿como responde generalmente?", options: ["Evita o explota", "Se incomoda y pospone el tema", "Habla cuando está más calmada", "Aborda el tema con claridad y empatia"], dimension: "Gestion Emocional", correct: 3 },
        { q: "¿Cuanto tiempo tarda en recuperarse emociónalmente despues de un día difícil?", options: ["Dias", "Horas", "Menos de una hora", "Minutos"], dimension: "Gestion Emocional", correct: 3 },
        { q: "Cuándo presenta una idea, ¿como se siente?", options: ["Insegura y nerviosa", "Con algo de nervio pero funcional", "Generalmente segura", "Muy segura y clara"], dimension: "Comúnicación Ejecutiva", correct: 3 },
        { q: "¿Con que frecuencia termina sus intervenciones con una pregunta de elevacion?", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente"], dimension: "Comúnicación Ejecutiva", correct: 3 },
        { q: "En reuniónes con jerarcas, ¿como habla?", options: ["Bajo y poco", "Con cuidado, midiendo cada palabra", "Con claridad cuando tiene algo que decir", "Con voz firme, pausas estratégicas y estructura"], dimension: "Comúnicación Ejecutiva", correct: 3 },
        { q: "¿Cuanto tiempo suele tardar en llegar al punto al hablar?", options: ["Mucho, se pierde en contexto", "Algo de tiempo", "Razonable", "Voy directa al punto"], dimension: "Comúnicación Ejecutiva", correct: 3 },
        { q: "Cuándo alguien la interrumpe, ¿que hace?", options: ["Se calla", "Se incomoda pero no hace nada", "Intenta retomar la palabra", "Recupera la palabra con educacion y firmeza"], dimension: "Comúnicación Ejecutiva", correct: 3 },
        { q: "Cuándo recibe feedback constructivo, ¿que pasa primero?", options: ["Se siente atacada", "Se incomoda pero lo escucha", "Lo procesa y extrae lo util", "Lo valora como oportunidad de crecimiento"], dimension: "Feedback y Candor", correct: 3 },
        { q: "¿Con que frecuencia pide feedback directo a su jefe o colegas?", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente"], dimension: "Feedback y Candor", correct: 3 },
        { q: "Cuándo da feedback a otros, ¿como lo hace?", options: ["Evita hacerlo", "Lo suaviza tanto que pierde sentido", "Lo dice con cuidado", "Lo dice con claridad y empatia"], dimension: "Feedback y Candor", correct: 3 },
        { q: "Si le dices una verdad incomoda, ¿como reaccióna?", options: ["Se cierra", "Se molestá internamente", "Te escucha aunque le cueste", "Lo agradece y reflexiona"], dimension: "Feedback y Candor", correct: 3 },
        { q: "¿Qué tan comoda está diciendo 'no estoy de acuerdo' en una reunión?", options: ["Muy incomoda", "Algo incomoda", "Comoda si tiene argumentos", "Muy comoda"], dimension: "Feedback y Candor", correct: 3 },
        { q: "Cuándo logra algo importante, ¿que piensa primero?", options: ["Fue suerte", "La ayudaron", "Trabajo duro", "Merecio esto por su competencia"], dimension: "Sindrome del Impostor", correct: 3 },
        { q: "¿Con que frecuencia teme que 'descubran' que no es tan capaz?", options: ["Muy frecuentemente", "Frecuentemente", "A veces", "Casi nunca"], dimension: "Sindrome del Impostor", correct: 3 },
        { q: "Antes de una presentacion importante, ¿como se siente?", options: ["Segura de que va a fracasar", "Nerviosa e insegura", "Nerviosa pero preparada", "Con confianza manejable"], dimension: "Sindrome del Impostor", correct: 3 },
        { q: "Si le piden que lídere un proyecto nuevo, ¿que siente?", options: ["Panico y rechazo", "Inseguridad", "Reto manejable", "Entusiasmo"], dimension: "Sindrome del Impostor", correct: 3 },
        { q: "¿Cómo compara su éxito con el de otros?", options: ["Siempre siente que les debe", "A veces siente que no merece estar ahi", "Reconoce que trabajo por esto", "Sabe que su esfuerzo y talento la trajeron ahi"], dimension: "Sindrome del Impostor", correct: 3 },
        { q: "¿Con que claridad identifica quienes tienen poder real en su organización?", options: ["No tengo idea", "Tengo una idea vaga", "Identifico a la mayoria", "Tengo un mapa claro"], dimension: "Influencia Politica", correct: 3 },
        { q: "¿Con que frecuencia construye alianzas estratégicas intencionalmente?", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente"], dimension: "Influencia Politica", correct: 3 },
        { q: "Cuándo necesita que algo se apruebe, ¿que hace?", options: ["Espera a que alguien más lo impulse", "Presenta la idea y espera", "Identifica a los decisores y prepara el terreno", "Construye apoyo antes de la reunión formal"], dimension: "Influencia Politica", correct: 3 },
        { q: "¿Qué tan comoda está navegando la 'politica' de su organización?", options: ["Muy incomoda", "Algo incomoda", "Comoda", "Muy comoda"], dimension: "Influencia Politica", correct: 3 },
        { q: "¿Tiene personas que hablen bien de ella cuando no está presente?", options: ["No lo se", "Pocas", "Algunas", "Varias y estratégicas"], dimension: "Influencia Politica", correct: 3 },
        { q: "¿Con que frecuencia sus logros son visibles para quienes deciden?", options: ["Casi nunca", "Rara vez", "A veces", "Frecuentemente"], dimension: "Visibilidad Estrategica", correct: 3 },
        { q: "Cuándo hace un buen trabajo, ¿como lo comúnica?", options: ["No lo comúnica", "Espera que otros lo noten", "Lo menciona modestamente", "Lo comparte con metricas e impacto"], dimension: "Visibilidad Estrategica", correct: 3 },
        { q: "¿Qué tan clara es su narrativa profesional?", options: ["No la tengo", "Tengo ideas dispersas", "Razonablemente clara", "Muy clara y comúnicada"], dimension: "Visibilidad Estrategica", correct: 3 },
        { q: "En eventos de la empresa, ¿como se relaciona?", options: ["Evita ir", "Va pero no interactua mucho", "Conversa con algunos colegas", "Aprovecha para conectar estratégicamente"], dimension: "Visibilidad Estrategica", correct: 3 },
        { q: "¿Tiene un sponsor o alguien que abra puertas por ella?", options: ["No", "No formalmente", "Posiblemente", "Si, de forma clara"], dimension: "Visibilidad Estrategica", correct: 3 },
        { q: "En su equipo, ¿se siente segura para decir 'no entiendo' o 'me equivoque'?", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente"], dimension: "Seguridad Psicologica", correct: 3 },
        { q: "Cuándo propone una idea diferente, ¿como la reciben?", options: ["La penalizan", "La ignoran", "La consideran", "La valoran"], dimension: "Seguridad Psicologica", correct: 3 },
        { q: "¿Con que frecuencia pide ayuda en su trabajo?", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente"], dimension: "Seguridad Psicologica", correct: 3 },
        { q: "Si comete un error, ¿que suele pasar?", options: ["La castigan", "La juzgan", "Se habla del error sin culparla", "Se aprende como equipo"], dimension: "Seguridad Psicologica", correct: 3 },
        { q: "¿Contribuye a crear seguridad psicologica para otras?", options: ["No", "Poco", "Algo", "Mucho"], dimension: "Seguridad Psicologica", correct: 3 },
        { q: "Cuándo negocia su salario o recursos, ¿cómo lo hace?", options: ["Acepta lo primero que le ofrecen", "Pide más pero cede rápidamente", "Negocia con datos pero le incomoda", "Negocia con firmeza, estrategia y naturalidad"], dimension: "Negociacion y Defensa de Valor", correct: 3 },
        { q: "¿Con qué frecuencia defiende el valor monetario o estratégico de su tiempo?", options: ["Nunca", "Rara vez", "A veces", "Frecuentemente"], dimension: "Negociacion y Defensa de Valor", correct: 3 },
        { q: "Si le piden un favor profesional que no le beneficia, ¿qué hace?", options: ["Dice que sí inmedíatamente", "Dice que sí pero se resiente", "Duda pero termina aceptando", "Dice que no con firmeza y elegancia"], dimension: "Negociacion y Defensa de Valor", correct: 3 },
        { q: "Al presentar una propuestá de proyecto, ¿cómo justifica la inversión?", options: ["Se enfoca solo en el costo", "Habla del esfuerzo que requerirá", "Menciona los beneficios vagamente", "Presenta un ROI claro y defiende el valor"], dimension: "Negociacion y Defensa de Valor", correct: 3 },
        { q: "¿Cobra o exige compensación justa por su experiencia adicional?", options: ["Nunca, lo hace gratis", "Rara vez", "A veces", "Siempre defiende su valor en el mercado"], dimension: "Negociacion y Defensa de Valor", correct: 3 },
        { q: "Cuándo lídera un proyecto, ¿cómo distribuye las tareas operativas?", options: ["Hace todo ella misma", "Delega pero micro-gestiona", "Delega tareas menores", "Delega responsabilidades completas con confianza"], dimension: "Delegacion y Empoderamiento", correct: 3 },
        { q: "¿Con qué frecuencia desarrolla a otros para que tomen su lugar?", options: ["Nunca", "Rara vez", "A veces", "Constantemente, es su prioridad"], dimension: "Delegacion y Empoderamiento", correct: 3 },
        { q: "Si su equipo comete un error, ¿qué asume ella?", options: ["Culpa al equipo", "Se frustra y asume la tarea ella", "Se responsabiliza pero no corrige el proceso", "Se responsabiliza y empodera al equipo para arreglarlo"], dimension: "Delegacion y Empoderamiento", correct: 3 },
        { q: "¿Qué tan indispensable se vuelve en la operación del día a día?", options: ["Totalmente indispensable", "Muy necesaria", "Ayuda pero el equipo funciona sin ella", "Su valor está en la estrategia, no en la operación"], dimension: "Delegacion y Empoderamiento", correct: 3 },
        { q: "Al empoderar a otros, ¿les da visibilidad por sus logros?", options: ["Se lleva el crédito", "Los menciona a veces", "Los reconoce pero minimiza", "Da crédito total y visible a su equipo"], dimension: "Delegacion y Empoderamiento", correct: 3 },
        { q: "Cuándo un proyecto importante fracasa, ¿cómo reaccióna?", options: ["Se hunde emociónalmente", "Busca culpables", "Se levanta pero pierde confianza", "Analiza, aprende y vuelve a intentarlo rápidamente"], dimension: "Resiliencia y Manejo del Fracaso", correct: 3 },
        { q: "¿Qué tanto miedo le tiene a equivocarse en público?", options: ["Le aterra, la paraliza", "Le da mucho miedo pero actúa", "Le preocupa moderadamente", "Lo ve como parte del proceso de crecimiento"], dimension: "Resiliencia y Manejo del Fracaso", correct: 3 },
        { q: "¿Con qué frecuencia se recupera de un revés sin perder el foco en su objetivo?", options: ["Nunca", "Rara vez", "A veces", "Casi siempre"], dimension: "Resiliencia y Manejo del Fracaso", correct: 3 },
        { q: "Si recibe un 'NO' a una iniciativa, ¿qué hace?", options: ["Abandona la idea para siempre", "Se queja del sistema", "Lo intenta una vez más sin cambios", "Itera su estrategia y busca otro ángulo"], dimension: "Resiliencia y Manejo del Fracaso", correct: 3 },
        { q: "Ante la presión y el estrés extremo sostenido, ¿cómo responde su salud física/mental?", options: ["Se quema (burnout) frecuentemente", "Sufre mucho pero resiste", "Logra mantener el equilibrio a medías", "Mantiene límites sanos y se cuida activamente"], dimension: "Resiliencia y Manejo del Fracaso", correct: 3 }
    ],
    planMap: {
        "Identidad de Liderazgo": "el Dia 1 (Identidad de líderazgo) y el Dia 37 (Agencia)",
        "Gestion Emocional": "el Dia 6 (Regulacion emociónal) y el Dia 15 (Empatia vs compasion)",
        "Comúnicación Ejecutiva": "el Dia 16 (Lenguaje no verbal) y el Dia 35 (Lenguaje de la agencia)",
        "Feedback y Candor": "el Dia 22 (Candor Radical) y el Dia 24 (Conversaciones difíciles)",
        "Sindrome del Impostor": "el Dia 4 (Impostor) y el Dia 31 (Tipos de impostora)",
        "Influencia Politica": "el Dia 28 (Feedback hacia arriba) y el Dia 57 (Mapa de capital social)",
        "Visibilidad Estrategica": "el Dia 29 (Proposito en 1 oracion) y el Dia 38 (Virtudes publicas)",
        "Seguridad Psicologica": "el Dia 8 (Seguridad psicologica) y el Dia 27 (Conversacion de accountabilidad)",
        "Negociacion y Defensa de Valor": "el Dia 14 (Negociacion de poder) y el Dia 42 (El valor de tu tiempo)",
        "Delegacion y Empoderamiento": "el Dia 19 (Suelto el control) y el Dia 45 (Mentoría inversa)",
        "Resiliencia y Manejo del Fracaso": "el Dia 10 (El fracaso como dato) y el Dia 60 (Antifragilidad)"
    }
};

// Autoevaluación: Mismas preguntas pero aplicadas a la mentora misma
DIAG_DATA.brechasAuto = DIAG_DATA.brechas.map(item => {
    return {
        ...item,
        q: item.q.replace(/ella/g, 'ti')
                 .replace(/ su /g, ' tu ')
                 .replace(/ la /g, ' te ')
                 .replace(/ le /g, ' te ')
    };
});
